### ISSUE TITLE
To have reliable and stable examples, a fixed iota-core version should be used

### ISSUE THREAD

**Issue by turnikuta** [iota-community/rust-iota-workshop#1]
Currently, the following dependency is used in Cargo.toml
```
iota-core = { git = "https://github.com/iotaledger/iota.rs" }
```

Any small change in this repository can therefore break the examples in the workshop. 
Currently, this is the case, with the last commit in iota.rs  https://github.com/iotaledger/iota.rs/commit/cbaf879423bd4f8a5dc9a9aa8cbdc460c34fcbdd

To ensure that all examples work reliably, the last tested version should always be configured. The current version is
```
 iota-core = "0.2.0-alpha.2"
```

If there is a new version, you can test all examples against the new version and then increase the version accordingly.

**Comment by Thoralf-M** [comment]
We just used `rev` now which is a commit so this issue can be closed I guess

**Comment by turnikuta** [comment]
That's  also fine - thx
